### PR TITLE
added Section activity and Section details activity

### PR DESCRIPTION
**Pull request by edoulaX**

### CODE REVIEW

**Review by villemontc — CHANGES_REQUESTED** [review]
Need to remove .idea/ files as they are not need in the repository.
Adding some tests and comments / documentation of the different class / methods

**Review by AdrianUlrich — CHANGES_REQUESTED** [review]
all ok but don't include .idea folder

**Comment by AdrianUlrich** [comment]
Also question, where did you get those flags and are they public domain?

**Review by AdrianUlrich — APPROVED** [review]
Requested changes have been met: I approve

Where did you get the flag images though, is that copyright-free?

**Review by rombirli — APPROVED** [review]
Good job !

**Comment by edoulaX** [comment]
pull request not needed as there is all the code on the pull request feature/add_section_test where I just added some code and tests.

**Pull request closed without merging**
