### PR TITLE
Translator implant using mlkit

### LINKED ISSUE #13: Connect to the choosen API to translate words
Subtask of #14

### PR DESCRIPTION
**Pull request by villemontc**
Firstly constructor is defined using src and dst language, we might use detection language later to avoid this.

Merging PR will close #13

### CODE REVIEW

**Review by AdrianUlrich — APPROVED** [review]

**Review by albastardoto — APPROVED** [review]
Yes

**Review by albastardoto — CHANGES_REQUESTED** [review]
In Translator.kt fun translate , remove custom implementation of async functions, no need as addOnSuccessListener and addOnFailureListenere is enough. No real need for TranslateListener

**Comment by villemontc** [comment]
> In Translator.kt fun translate , remove custom implementation of async functions, no need as addOnSuccessListener and addOnFailureListenere is enough. No real need for TranslateListener

@albastardoto , can we admit this and merge, there is an issue #35 created to handle this work with @AdrianUlrich .

**Review by AdrianUlrich — APPROVED** [review]
Async testing not handled optimally, but will be corrected in #35

**Review by rombirli — COMMENTED** [review]
I think that it is a bit more clean to make Translator.translate return a task<String> Instead of taking a Listener as arguments

**Comment by AdrianUlrich** [comment]
> I think that it is a bit more clean to make Translator.translate return a task Instead of taking a Listener as arguments

@rombirli 

> Async testing not handled optimally, but will be corrected in #35

As in, it's not that bad, people. Just approve this s*** so we can start working on it before I lose my mind.

**Review by rombirli — APPROVED** [review]

**Pull request merged**
