### PR TITLE
Feature/camera text detection

### PR DESCRIPTION
**Pull request by edoulaX**

### CODE REVIEW

**Review by AdrianUlrich — CHANGES_REQUESTED** [review]
You're having a problem with your view, as espresso can't find your view

```NoMatchingViewException: No views in hierarchy found matching```
on line 102 of TextDetectionActivityTest.kt

**Review by albastardoto — APPROVED** [review]
Looks alright, should probably look into using coroutines in TextDetectionActivity if possible

**Review by AdrianUlrich — APPROVED** [review]
Changes were made as requested.
Though you have some unused imports and unformatted code that could be automatically cleaned up.

**Comment by edoulaX** [comment]
it detect text on the image

**Pull request merged**
