### PR TITLE
Firebase RealTimeDatabase Integrated

### PR DESCRIPTION
**Pull request by AdrianUlrich**
I guess I should make some activity but it already took me 8 hours just for this ^^'

### CODE REVIEW

**Review by albastardoto — APPROVED** [review]
Good work, should put firestore database link in a constant or config file.

**Comment by AdrianUlrich** [comment]
Will make more tests in #72

**Review by edoulaX — APPROVED** [review]
What is the "@Suppress("UNUSED_PARAMETER")", otherwise good work and try to add some more test

**Comment by AdrianUlrich** [comment]
> What is the "@Suppress("UNUSED_PARAMETER")"
It suppresses the warning for the view parameter never being used, required by android but not understood by linter

**Pull request merged**
